version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - '*'
    # Ignore dependency patches
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
