[package]
name = "lc3sim"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lc3sim_project"
path = "src/lib.rs"

[[bin]]
name = "lc3sim"
path = "src/cli.rs"

[dependencies]
anyhow = "1.0.95"
once_cell = "1.20.2"
regex = "1.11.1"
thiserror = "2"
