[package]
name = "lc3sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lc3sim_project"
path = "src/lib.rs"

[[bin]]
name = "lc3sim"
path = "src/cli.rs"

[dependencies]

